services:
  _defaults:
    autowire: true
    autoconfigure: true

  Hippocampe\Bundle\PageBundle\Controller\Admin\:
    resource: '../../Controller/Admin/*'
    tags: [ 'controller.service_arguments' ]

  Hippocampe\Bundle\PageBundle\Controller\:
    resource: '../../Controller/*'
    tags: [ 'controller.service_arguments' ]

  Hippocampe\Bundle\PageBundle\Repository\:
    resource: '../../Repository/*'
    tags: [ 'doctrine.repository_service' ]

  Hippocampe\Bundle\PageBundle\Form\Admin\Type\Chart\PieChartRowType:
    arguments:
      $colors: '%page.sections.colors%'

  Hippocampe\Bundle\PageBundle\Form\Admin\Type\Chart\BarChartRowType:
    arguments:
      $colors: '%page.sections.colors%'

  Hippocampe\Bundle\PageBundle\Form\Admin\Type\Chart\BarChartYRowType:
    arguments:
      $colors: '%page.sections.colors%'

  Hippocampe\Bundle\PageBundle\Form\Admin\Type\Chart\LineChartRowType:
    arguments:
      $colors: '%page.sections.colors%'

  twig.extension:
    class: Hippocampe\Bundle\PageBundle\Twig\PageBundleTwigExtension
    tags:
      - { name: twig.extension }
    arguments:
      $spacer: '%page.sections.spacer%'