parameters:
  app.path.section_image: /uploads/section_image

vich_uploader:
  mappings:
    section_image:
      uri_prefix: '%app.path.section_image%'
      upload_destination: '%kernel.project_dir%/public/uploads/section_image'
      namer: Vich\UploaderBundle\Naming\OrignameNamer